@extends('layouts.app2')
@section('title',$titulo)
@section('content')
    @switch($contenido)
        @case('index')
            @include('rules.panel-card')
            @include('notices.panel-card')
            @include('post.panel-card')
            @break
        @case('posts')
            @include('post.panel-card')
            @break
        @case('notices')
            @include('notices.panel-card')
            @break
        @case('rules')
            @include('rules.panel-card')
            @break
        @case('teachers')
            @include('home.teachers')
            @break
        @case('devs')
            @include('home.devs')
            @break
        @case('sectionPartners')
            @include('home.section-partners')
            @break
        @case('users')
            @include('user.showUsers')
            @break
    @endswitch
@endsection()

